#!/usr/bin/env python3
"""
Ollama + Gradio + MCP Serial Tool

- Launches Ollama as a subprocess
- Queries qwen3:4b-instruct model
- Hosts a Gradio webserver with:
    1. Textbox for general Q&A with Ollama
    2. Textbox for trajectory requests → motion commands
       (generated by Ollama with a fixed system prompt)
       and sent via serial to the robot

Requirements:
- Ollama installed locally
- qwen3:4b-instruct pulled via `ollama pull qwen3:4b-instruct`
- Python 3.12+ with requests, gradio, pyserial installed
"""

import subprocess
import requests
import time
import atexit
import sys
import gradio as gr
import serial
from pathlib import Path

OLLAMA_API_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "qwen3:4b-instruct"

ollama_process = None

# Configuration
g_s_port = "/dev/ttyS4"
g_n_baudrate = 115200

def load_system_prompt(i_s_path="system_prompt.txt") -> str:
    """Load motion system prompt from file."""
    try:
        return Path(i_s_path).read_text(encoding="utf-8")
    except Exception as e:
        print(f"⚠️ Could not load system prompt: {e}")
        return "You are a model whose job is to generate motion commands."

g_s_motion_system_prompt : str = load_system_prompt("system_prompt.txt")

#--------------------------------------------------------------

def parse_command(command: str) -> Tuple[bool, int, int, int]:
    """
    Parse a string like 'VT25R+5L+5/0' and return (success, T, R, L).
    Handles trailing '/0' and malformed input gracefully.
    """
    try:
        # Ignore trailing terminator if present
        if command.endswith("/0"):
            command = command[:-2]

        # Find markers
        t_start = command.index("VT") + 2
        r_start = command.index("R")
        l_start = command.index("L")

        # Slice out substrings
        t_str = command[t_start:r_start].strip()
        r_str = command[r_start+1:l_start].strip()
        l_str = command[l_start+1:].strip()

        # Validate presence
        if not (t_str and r_str and l_str):
            return False, 0, 0, 0

        # Convert to integers
        t_val = int(t_str)
        r_val = int(r_str)
        l_val = int(l_str)

        return True, t_val, r_val, l_val

    except (ValueError, IndexError):
        return False, 0, 0, 0

# --- Ollama management ---
def start_ollama():
    global ollama_process
    try:
        ollama_process = subprocess.Popen(
            ["ollama", "serve"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        time.sleep(2)
        print("✅ Ollama server started.")
    except Exception as e:
        print(f"Failed to start Ollama: {e}")
        sys.exit(1)

def stop_ollama():
    global ollama_process
    if ollama_process:
        ollama_process.terminate()
        try:
            ollama_process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            ollama_process.kill()
        print("🛑 Ollama server stopped.")

    return False #OK

# --- Query functions ---
def query_ollama(prompt: str) -> str:
    """General Q&A with Ollama."""
    payload = {"model": MODEL_NAME, "prompt": prompt, "stream": False}
    try:
        response = requests.post(OLLAMA_API_URL, json=payload)
        response.raise_for_status()
        return response.json().get("response", "")
    except requests.exceptions.RequestException as e:
        return f"Error communicating with Ollama: {e}"

def generate_motion_commands(request: str) -> str:
    """Trajectory → motion commands via Ollama, then send over serial."""
    payload = {
        "model": MODEL_NAME,
        "prompt": f"{g_s_motion_system_prompt}\nUser request: {request}",
        "stream": False
    }

    l_s_commands :List[str] = list()

    #ask the LLM model

    try:
        response = requests.post(OLLAMA_API_URL, json=payload)
        response.raise_for_status()
        motions = response.json().get("response", "")
        # Send each line to serial
        for line in motions.strip().splitlines():
            if line.strip():
                l_s_commands.append(line)
                #send_serial_command(line.strip() + "\n")
        
    except requests.exceptions.RequestException as e:
        return f"Error communicating with Ollama: {e}"

    #here I have a list of commands to send, it's bad but it doesn't matter for the MVP

    with serial.Serial(
            g_s_port,
            baudrate=g_n_baudrate,
            timeout=1  # Timeout for read operations
        ) as cl_serial:
            for s_command in l_s_commands:
                success, t_val, r_val, l_val = parse_command(s_command)
                if success:
                    # Example: repack into new command
                    s_reparsed_command = f"VT{t_val}R{r_val}L{l_val}\0".encode("ascii")
                    cl_serial.write(s_reparsed_command)  # uncomment for real serial
                    print(f"➡️ Sent: {s_reparsed_command}")
                else:
                    print(f"❌ Failed to parse: {s_command}")

    return motions

# --- Main ---
def main():
    start_ollama()
    atexit.register(stop_ollama)

    iface = gr.TabbedInterface(
        [
            gr.Interface(
                fn=query_ollama,
                inputs=gr.Textbox(lines=3, placeholder="Ask Ollama anything..."),
                outputs=gr.Textbox(lines=10, label="Model Response"),
                title="🧠 Ollama Q&A"
            ),
            gr.Interface(
                fn=generate_motion_commands,
                inputs=gr.Textbox(lines=3, placeholder="Describe a trajectory..."),
                outputs=gr.Textbox(lines=10, label="Motion Commands"),
                title="🤖 Motion Planner (MCP Tool)"
            )
        ],
        tab_names=["RAMIE Specifications", "Motion Commands"]
    )

    iface.launch(server_name="0.0.0.0", server_port=7860)

if __name__ == "__main__":
    main()
