#!/usr/bin/env python3
"""
Ollama + Gradio + MCP Serial Tool

- Launches Ollama as a subprocess
- Queries qwen3:4b-instruct model
- Hosts a Gradio webserver with:
    1. Textbox for general Q&A with Ollama
    2. Textbox for trajectory requests → motion commands
       (generated by Ollama with a fixed system prompt)
       and sent via serial to the robot

Requirements:
- Ollama installed locally
- qwen3:4b-instruct pulled via `ollama pull qwen3:4b-instruct`
- Python 3.12+ with requests, gradio, pyserial installed
"""

import subprocess
import requests
import time
import atexit
import sys
import gradio as gr
from pathlib import Path

OLLAMA_API_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "qwen3:4b-instruct"

ollama_process = None

# --- Serial setup ---
SERIAL_PORT = "/dev/ttyUSB0"   # adjust to your robot’s port
BAUD_RATE = 115200
ser = None

def load_system_prompt(i_s_path="system_prompt.txt") -> str:
    """Load motion system prompt from file."""
    try:
        return Path(i_s_path).read_text(encoding="utf-8")
    except Exception as e:
        print(f"⚠️ Could not load system prompt: {e}")
        return "You are a model whose job is to generate motion commands."

g_s_motion_system_prompt : str = load_system_prompt("system_prompt.txt")

def start_serial():
    global ser
    try:
        ser = serial.Serial(SERIAL_PORT, BAUD_RATE, timeout=1)
        print(f"✅ Serial connected on {SERIAL_PORT}")
    except Exception as e:
        print(f"Failed to open serial port: {e}")
        ser = None

def send_serial_command(cmd: str):
    """Send a single command string to the robot over UART."""
    print(f"➡️ Sent: {cmd.strip()}")


# --- Ollama management ---
def start_ollama():
    global ollama_process
    try:
        ollama_process = subprocess.Popen(
            ["ollama", "serve"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        time.sleep(2)
        print("✅ Ollama server started.")
    except Exception as e:
        print(f"Failed to start Ollama: {e}")
        sys.exit(1)

def stop_ollama():
    global ollama_process
    if ollama_process:
        ollama_process.terminate()
        try:
            ollama_process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            ollama_process.kill()
        print("🛑 Ollama server stopped.")
    if ser and ser.is_open:
        ser.close()
        print("🛑 Serial closed.")

# --- Query functions ---
def query_ollama(prompt: str) -> str:
    """General Q&A with Ollama."""
    payload = {"model": MODEL_NAME, "prompt": prompt, "stream": False}
    try:
        response = requests.post(OLLAMA_API_URL, json=payload)
        response.raise_for_status()
        return response.json().get("response", "")
    except requests.exceptions.RequestException as e:
        return f"Error communicating with Ollama: {e}"

def generate_motion_commands(request: str) -> str:
    """Trajectory → motion commands via Ollama, then send over serial."""
    payload = {
        "model": MODEL_NAME,
        "prompt": f"{g_s_motion_system_prompt}\nUser request: {request}",
        "stream": False
    }
    try:
        response = requests.post(OLLAMA_API_URL, json=payload)
        response.raise_for_status()
        motions = response.json().get("response", "")
        # Send each line to serial
        for line in motions.strip().splitlines():
            if line.strip():
                send_serial_command(line.strip() + "\n")
        return motions
    except requests.exceptions.RequestException as e:
        return f"Error communicating with Ollama: {e}"

# --- Main ---
def main():
    start_ollama()
    start_serial()
    atexit.register(stop_ollama)

    iface = gr.TabbedInterface(
        [
            gr.Interface(
                fn=query_ollama,
                inputs=gr.Textbox(lines=3, placeholder="Ask Ollama anything..."),
                outputs=gr.Textbox(lines=10, label="Model Response"),
                title="🧠 Ollama Q&A"
            ),
            gr.Interface(
                fn=generate_motion_commands,
                inputs=gr.Textbox(lines=3, placeholder="Describe a trajectory..."),
                outputs=gr.Textbox(lines=10, label="Motion Commands"),
                title="🤖 Motion Planner (MCP Tool)"
            )
        ],
        tab_names=["General Q&A", "Motion Commands"]
    )

    iface.launch(server_name="0.0.0.0", server_port=7860)

if __name__ == "__main__":
    main()
