#!/usr/bin/env python3
"""
Ollama + Gradio + MCP Serial Tool

- Launches Ollama as a subprocess
- Queries qwen3:4b-instruct model
- Hosts a Gradio webserver with:
    1. Textbox for general Q&A with Ollama
    2. Textbox for trajectory requests → motion commands
       (generated by Ollama with a fixed system prompt)
       and sent via serial to the robot

Requirements:
- Ollama installed locally
- qwen3:4b-instruct pulled via `ollama pull qwen3:4b-instruct`
- Python 3.12+ with requests, gradio, pyserial installed
"""

import subprocess
import requests
import time
import atexit
import sys
import gradio as gr
import serial
from pathlib import Path
from typing import Tuple, List

# Ollama API
OLLAMA_API_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "qwen3:4b-instruct"

ollama_process = None

# Serial config
g_s_port = "/dev/ttyS4"
g_n_baudrate = 115200

def load_system_prompt(i_s_path="system_prompt.txt") -> str:
    """Load motion system prompt from file."""
    try:
        return Path(i_s_path).read_text(encoding="utf-8")
    except Exception as e:
        print(f"⚠️ Could not load system prompt: {e}")
        return "You are a model whose job is to generate motion commands."

g_s_motion_system_prompt: str = load_system_prompt("system_prompt.txt")

g_s_ramie_system_prompt : str = load_system_prompt("robot_specification.json")

#--------------------------------------------------------------

from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
from llama_index.llms.ollama import Ollama
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

def build_ramie_index(spec_file="robot_specifications.txt"):
    try:
        docs = SimpleDirectoryReader(input_files=[spec_file]).load_data()

        # Use a small HuggingFace embedding model (CPU-friendly)
        embed_model = HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L6-v2")

        # Build index with embeddings only
        index = VectorStoreIndex.from_documents(docs, embed_model=embed_model)

        # Use a smaller Ollama model for answering specs if needed
        llm = Ollama(model="qwen3:4b-instruct", request_timeout=30.0)

        return index, llm
    except Exception as e:
        print(f"⚠️ Failed to build RAMIE index: {e}")
        return None, None

ramie_index, ramie_llm = build_ramie_index()

def query_ramie_specs(question: str) -> str:
    if not ramie_index:
        return "RAMIE index not available."
    try:
        query_engine = ramie_index.as_query_engine(llm=ramie_llm)
        response = query_engine.query(question)
        return str(response)
    except Exception as e:
        return f"Error querying RAMIE specs: {e}"

#--------------------------------------------------------------

def parse_command(command: str) -> Tuple[bool, int, int, int]:
    """
    Parse a string like 'VT25R+5L+5/0' and return (success, T, R, L).
    Handles trailing '/0' and malformed input gracefully.
    """
    try:
        if command.endswith("/0"):
            command = command[:-2]

        t_start = command.index("VT") + 2
        r_start = command.index("R")
        l_start = command.index("L")

        t_str = command[t_start:r_start].strip()
        r_str = command[r_start+1:l_start].strip()
        l_str = command[l_start+1:].strip()

        if not (t_str and r_str and l_str):
            return False, 0, 0, 0

        t_val = int(t_str)
        r_val = int(r_str)
        l_val = int(l_str)

        return True, t_val, r_val, l_val

    except (ValueError, IndexError):
        return False, 0, 0, 0

# --- Ollama management ---
def start_ollama():
    global ollama_process
    try:
        ollama_process = subprocess.Popen(
            ["ollama", "serve"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        time.sleep(2)
        print("✅ Ollama server started.")
    except Exception as e:
        print(f"Failed to start Ollama: {e}")
        sys.exit(1)

def stop_ollama():
    global ollama_process
    if ollama_process:
        ollama_process.terminate()
        try:
            ollama_process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            ollama_process.kill()
        print("🛑 Ollama server stopped.")
    return False

# --- Query functions ---
def query_ollama(prompt: str) -> str:
    """General Q&A with Ollama."""
    payload = {"model": MODEL_NAME, "prompt": prompt, "stream": False}
    try:
        response = requests.post(OLLAMA_API_URL, json=payload)
        response.raise_for_status()
        return response.json().get("response", "")
    except requests.exceptions.RequestException as e:
        return f"Error communicating with Ollama: {e}"


def query_ramie_llamaindex(i_s_prompt: str):

    if not ramie_index:
        pass

    payload = {
        "model": MODEL_NAME,
        "prompt": f"{g_s_ramie_system_prompt}\nUser request: {i_s_prompt}",
        "stream": False
    }

    l_s_commands: List[str] = []

    try:
        response = requests.post(OLLAMA_API_URL, json=payload)
        response.raise_for_status()
        answer = response.json().get("response", "")
    except requests.exceptions.RequestException as e:
        return f"Error communicating with Ollama: {e}"

    return answer

def generate_motion_commands(request: str) -> str:
    """Trajectory → motion commands via Ollama, then send over serial."""
    payload = {
        "model": MODEL_NAME,
        "prompt": f"{g_s_motion_system_prompt}\nUser request: {request}",
        "stream": False
    }

    l_s_commands: List[str] = []

    try:
        response = requests.post(OLLAMA_API_URL, json=payload)
        response.raise_for_status()
        motions = response.json().get("response", "")
        for line in motions.strip().splitlines():
            if line.strip():
                l_s_commands.append(line)
    except requests.exceptions.RequestException as e:
        return f"Error communicating with Ollama: {e}"

    with serial.Serial(
        g_s_port,
        baudrate=g_n_baudrate,
        timeout=1
    ) as cl_serial:
        for s_command in l_s_commands:
            success, t_val, r_val, l_val = parse_command(s_command)
            if success:
                s_reparsed_command = f"VT{t_val}R{r_val}L{l_val}\0".encode("ascii")
                cl_serial.write(s_reparsed_command)
                print(f"➡️ Sent: {s_reparsed_command}")
            else:
                print(f"❌ Failed to parse: {s_command}")

    return motions

# --- Main ---
def main():
    start_ollama()
    atexit.register(stop_ollama)

    iface = gr.TabbedInterface(
        [
            gr.Interface(
                fn=query_ramie_llamaindex,
                inputs=gr.Textbox(lines=3, placeholder="Ask about RAMIE specs..."),
                outputs=gr.Textbox(lines=10, label="RAMIE Answer"),
                title="📑 RAMIE Specifications"
            ),
            gr.Interface(
                fn=generate_motion_commands,
                inputs=gr.Textbox(lines=3, placeholder="Describe a trajectory..."),
                outputs=gr.Textbox(lines=10, label="Motion Commands"),
                title="🤖 Motion Planner (MCP Tool)"
            )
        ],
        tab_names=["RAMIE Specifications", "Motion Commands"]
    )

    iface.launch(server_name="0.0.0.0", server_port=7860)

if __name__ == "__main__":
    main()
